name: Periodic Update

on:
  schedule:
    - cron: '0 0 * * 1'  # weekly, monday midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run update script
        run: bash update.sh

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git add -A
          git commit -m "freedownloadmanager: bump to $(grep -oP '(?<=version = ")[\d.]+' package.nix)"
          git push
